### PR TITLE
mozsocial-android removed Glean integration

### PR DESCRIPTION
**Pull request by badboy**
Removal done here: https://github.com/MozillaSocial/mozilla-social-android/pull/570

### CODE REVIEW

**Review by Dexterp37 — APPROVED** [review]
Why do we need to remove the file given that it's deprecated?

**Comment by badboy** [comment]
> Why do we need to remove the file given that it's deprecated?

because `probe_scraper.check_repositories` doesn't skip deprecated repos (I'll file a bug).

**Comment by badboy** [comment]
Oh wait, it does, we just need the deprecated in the right place: https://github.com/mozilla/probe-scraper/blob/51e50ed7beb9ccb5751dc4e68e53531edcad9916/probe_scraper/check_repositories.py#L35

**Comment by badboy** [comment]
D'oh! it was still deprecated, #727 did only half the job of undoing that.

**Pull request closed without merging**
