### PR TITLE
Bug 1763467 Added moz_pipeline_metadata and moz_pipeline_metadata_default to repository definition

### PR DESCRIPTION
**Pull request by gleonard-m**
Added moz_pipeline_metadata and moz_pipeline_metadata_default to repository definition.

### CODE REVIEW

**Comment by jklukas** [comment]
The diff here is empty, even though there are some commits listed. The commits listed are mostly merges and go back pretty far in history. So something strange is going on here and there may be a mismatch between history in your branch and the current state of `main` here.

**Comment by gleonard-m** [comment]
Yes, this PR is still in draft (because of the series of commits).  There is another PR https://github.com/mozilla/probe-scraper/pull/424 that is the correct PR.

This PR can be closed as a no-op.

**Comment by Alan061989** [comment]
Eu em fase de aprendizado

**Comment by Dexterp37** [comment]
> This PR can be closed as a no-op.

✅

**Pull request closed without merging**
