### PR TITLE
Update glean_parser req to v3.0.0 to properly parse v2 definitions files

### PR DESCRIPTION
**Pull request by chutten**

### CODE REVIEW

**Review by fbertsch — APPROVED** [review]
I'm assuming everything is backwards compatible still?

**Comment by fbertsch** [comment]
@chutten that is, `glean_parse` won't barf on historic definition files.

**Comment by chutten** [comment]
Tests pass, and the dry-run is... still dryly running.

The non-backwards-compatible change is the removal of the JWE metric type. Which no one uses.

**Comment by chutten** [comment]
@badboy to confirm that I have that right.

**Comment by badboy** [comment]
Confirmed. So I hope no one ever used `type: jwe` in a scanned metrics.yaml

**Comment by chutten** [comment]
Still waiting on this dry run. All the way up to `firefox-reality-pc`, now, so I hope it won't be much longer.

**Comment by fbertsch** [comment]
@chutten you're dry-running locally? That does take awhile if you include any mozilla-central repositories (geckoview, desktop, etc.).

**Comment by chutten** [comment]
I am, yes. I'm following the instructions in the `README`. It didn't tell me to only run against some repos (or how)

**Comment by chutten** [comment]
It completed (while I was having lunch)!

**Pull request merged**
