### PR TITLE
Update vendored parsers

### PR DESCRIPTION
**Pull request by relud**
restores #374 and adds patches for legacy support in ff01394

### CODE REVIEW

**Comment by relud** [comment]
works with `python -m probe_scraper.runner --out-dir temp/probe_data/ --cache-dir temp/probe_cache/ --moz-central --firefox-channel release`. test run without `--firefox-channel release` is still downloading revisions.

**Review by chutten — APPROVED** [review]
I only really looked closely at https://github.com/mozilla/probe-scraper/commit/ff01394a15e3e5a8e276b10fb109a469a63030a9, assuming the rest is identical to the reverted patch.

**Comment by relud** [comment]
note for later me: this is not working with nightly due to a string/int type mismatch

**Comment by relud** [comment]
i'm going to close this in favor of dealing with it after the refactor

**Pull request closed without merging**
