### PR TITLE
Added optional "prototype" property

### PR DESCRIPTION
**Pull request by singhvaishnavi**
Solution to issue #244

### CODE REVIEW

**Comment by singhvaishnavi** [comment]
@brizental Can you please review this?

**Review by brizental — CHANGES_REQUESTED** [review]
Hey @singhvaishnavi great job! The implementation looks correct to me. 

Can you please change `glean-js` to `prototype: true`. That is the only prototype app that we have at the moment.

**Comment by singhvaishnavi** [comment]
Hey @brizental I made the requested changes. Please take a look.

**Review by brizental — APPROVED** [review]
LGTM!

**Pull request merged**
