### PR TITLE
Support filtering glean repos by url

### PR DESCRIPTION
**Pull request by relud**

### CODE REVIEW

**Comment by Dexterp37** [comment]
@relud is this in service of the "triggered pull" ("push model"?)

**Comment by relud** [comment]
> @relud is this in service of the "triggered pull" ("push model"?)

yes, i'm currently working on breaking down breaking that feature down into more manageable pieces that can be merged separately.

**Review by chutten — APPROVED** [review]
Do you think this warrants an example in README?

**Comment by relud** [comment]
> Do you think this warrants an example in README?

I don't think so. The [Performing a Dry-Run](https://github.com/mozilla/probe-scraper/blob/main/README.md#performing-a-dry-run) section is already kind of long, and doesn't cover all of the cli options available. I think this one is fine to leave out for now. I'll probably add an example that uses `--glean-url` when I add `--glean-commit` and `--glean-commit-branch` in another PR.

**Pull request merged**
