### PR TITLE
Scrape processes, alert_emails, and bucket enumeration

### PR DESCRIPTION
**Pull request by fbertsch**
Also fixes a bug in the histogram_tools that used `definition`
instead of `_definition`.

Tested this locally, output seems to be good.

### CODE REVIEW

**Comment by chutten** [comment]
Do... do we want emails?

**Comment by fbertsch** [comment]
@chutten definitely, it would help a lot of people to get name or email in the probe-dictionary, so they know who to ask questions to. Should make our lives a bit easier too!

**Comment by fbertsch** [comment]
hmm, tests are failing, and it looks like the output does not actually have `notification_emails`. Investigating.

**Comment by chutten** [comment]
It's called `alert_emails` in Histograms, I think.

I wonder if publishing emails on the probe info service and probe dictionary is any different than having them published on hg.mo

**Comment by fbertsch** [comment]
Okay, squashed the commits. The output has the expected fields now, the tests pass.

**Comment by fbertsch** [comment]
@chutten do you mean a privacy concern? Or..?

**Comment by fbertsch** [comment]
Fixes #42 and #26

**Comment by chutten** [comment]
Privacy not so much as ease of scraping. Which might not be something we worry about in 2019 as much as I remember worrying about it in 2009

**Comment by fbertsch** [comment]
I'd wager that the `histograms.json` and `scalars.yaml` files are more likely to be scraped than the probe-info-service data, since they are in moz-central.

**Comment by chutten** [comment]
Fair enough.

**Comment by Dexterp37** [comment]
Since the privacy discussion has settled, I think we can merge this :) LGTM!

**Pull request merged**
