### PR TITLE
FOGotype is dead, long live Project FOG

### PR DESCRIPTION
**Pull request by badboy**
Is it safe to just remove it?
We deactivated it on Firefox Nightly a while ago and are not interested in any of that data anymore.

### CODE REVIEW

**Comment by chutten** [comment]
If pipeline says we can remove it, then we should.

@fbertsch can we also deep-six the data that's already in BQ? Is there a process for that?

**Comment by fbertsch** [comment]
@chutten that will happen automatically! This is a bit of new territory for us, so no official process in place.

**Comment by jklukas** [comment]
> Can we also deep-six the data that's already in BQ? Is there a process for that?

cc @whd. I don't believe we've yet done this in prod, and there may be some hand-holding needed to get out terraform state into shape to handle the deletion of tables/datasets.

**Comment by chutten** [comment]
Oh wait I see that this will happen automagically in the bug. Whoops.

**Comment by whd** [comment]
> cc @whd. I don't believe we've yet done this in prod, and there may be some hand-holding needed to get out terraform state into shape to handle the deletion of tables/datasets.

We haven't done this in prod, but the process is the same as stage where we've done this three or four times. I've mentioned it in https://bugzilla.mozilla.org/show_bug.cgi?id=1626490#c8 and if @mreid-moz signs off I will allow this deletion to propagate to stage and prod.

**Comment by whd** [comment]
@mreid-moz signed off on the deletion in https://bugzilla.mozilla.org/show_bug.cgi?id=1626490#c12 so I think we're good to proceed from a procedural perspective (I see tests are failing however).

**Pull request merged**
