### PR TITLE
Add explicit retention to all glean apps

### PR DESCRIPTION
**Pull request by whd**
https://mozilla-hub.atlassian.net/browse/SRELEAD-182?focusedCommentId=897713

### CODE REVIEW

**Comment by whd** [comment]
Deployment plan in https://mozilla-hub.atlassian.net/browse/SRELEAD-182?focusedCommentId=901771

**Review by badboy — APPROVED** [review]
Should this become a required field in the schema? (`probeinfo_api.yaml`)

**Review by akkomar — APPROVED** [review]

**Comment by akkomar** [comment]
> Should this become a required field in the schema? (`probeinfo_api.yaml`)

Seems like we should unless we want to repeat this process at some point.

**Comment by whd** [comment]
>  Should this become a required field in the schema? (probeinfo_api.yaml)

It probably should. If I set that to required will CI automatically fail if it's not specified?

At any rate, I want to land this as-is before making it required or adding a CI check since I deliberately skipped some apps that should be removed in the near future (rally).

**Comment by badboy** [comment]
> > Should this become a required field in the schema? (probeinfo_api.yaml)
> 
> It probably should. If I set that to required will CI automatically fail if it's not specified?
> 
> At any rate, I want to land this as-is before making it required or adding a CI check since I deliberately skipped some apps that should be removed in the near future (rally).

It should! And yeah, should have been explicit: landing this as a followup sounds good to me!

**Pull request merged**
