### PR TITLE
Deprecate viu-politica and ignore commit that removed data collection

### PR DESCRIPTION
**Pull request by badboy**

### CODE REVIEW

**Comment by badboy** [comment]
Failing on the VPN stuff, will be fixed in #576

**Comment by Dexterp37** [comment]
Before merging this let me double check this is actually deprecated. Do we delete stuff if we mark things as deprecated?

**Review by travis79 — APPROVED** [review]
Looks good to me... provided @Dexterp37's concern is 👍

**Comment by badboy** [comment]
> Looks good to me... provided @Dexterp37's concern is 👍

I already removed the deprecation, we can still do that afterwards.

**Pull request merged**
