### PR TITLE
Reland library names refactoring

### PR DESCRIPTION
**Pull request by wlach**

### CODE REVIEW

**Comment by wlach** [comment]
This is basically #278, with a few cleanups I missed the first time around as well as some minor updates to the newly-landed integration test. It is currently failing CI (since I took out the updated duplicate logic and put it into #290) but it should start passing when that merges.

**Comment by jklukas** [comment]
Can you give me some more context on what has changed? Was yesterday's failing test due to a real problem, or a flaw in the testing logic? Is #290 the material change that will lead to a successful deploy, or do the cleanups in this PR have functional effect compared to #278?

**Comment by wlach** [comment]
> Can you give me some more context on what has changed? Was yesterday's failing test due to a real problem, or a flaw in the testing logic? Is #290 the material change that will lead to a successful deploy, or do the cleanups in this PR have functional effect compared to #278?

It was a flaw in the testing logic. #290 is the material change (explained in the commits: tl;dr our duplicate metric checks incorrectly considered removed metrics), this PR just has some slight cleanups in the repositories.yaml specification.

**Review by jklukas — APPROVED** [review]

**Review by fbertsch — APPROVED** [review]
LGTM, but let's wait to merge until Monday so if things go wrong again Wesley doesn't have to look in to things on Sunday.

**Comment by wlach** [comment]
> LGTM, but let's wait to merge until Monday so if things go wrong again Wesley doesn't have to look in to things on Sunday.

Makes sense, maybe we can land #290 today though, assuming it looks good? It's waiting for a review.

**Pull request merged**
