### PR TITLE
Bug 1592705 - Add vrbrowser app id

### PR DESCRIPTION
**Pull request by mreid-moz**
I'm not sure about the "dependencies" piece - I used [this code](https://github.com/MozillaReality/FirefoxReality/blob/master/versions.gradle#L54-L67) as reference.

### CODE REVIEW

**Comment by Dexterp37** [comment]
@mdboom do we have a document somewhere that mentions the Gradle command to list out the dependencies?

**Comment by Dexterp37** [comment]
For context, here's the list of [deps](https://github.com/MozillaReality/FirefoxReality/blob/72efce962cb4ade87a24ca5af2db4b2eef86f21a/app/build.gradle#L449-L462) by the app itself.

Apparently, we just have:

- Glean SDK
- support-sync

So we should add:

```
    - org.mozilla.components:service-glean
    - org.mozilla.components:support-sync-telemetry
```

**Comment by mdboom** [comment]
> @mdboom do we have a document somewhere that mentions the Gradle command to list out the dependencies?

It's `./gradlew :app:dependencies`.  We should document this somewhere -- I guess here in the probe-scraper docs.

**Comment by mdboom** [comment]
Here's the complete dependencies list of FirefoxReality, for reference:

```
+--- androidx.test:runner:1.1.0-alpha4
|    +--- androidx.annotation:annotation:1.0.0-alpha1 -> 1.1.0
|    +--- androidx.test:monitor:1.1.0-alpha4
|    |    \--- androidx.annotation:annotation:1.0.0-alpha1 -> 1.1.0
|    +--- junit:junit:4.12
|    |    \--- org.hamcrest:hamcrest-core:1.3
|    \--- net.sf.kxml:kxml2:2.3.0
+--- androidx.test.espresso:espresso-core:3.1.0-alpha4
|    +--- androidx.test:runner:1.1.0-alpha4 (*)
|    +--- androidx.test.espresso:espresso-idling-resource:3.1.0-alpha4
|    +--- com.squareup:javawriter:2.1.1
|    +--- javax.inject:javax.inject:1
|    +--- org.hamcrest:hamcrest-library:1.3
|    |    \--- org.hamcrest:hamcrest-core:1.3
|    +--- org.hamcrest:hamcrest-integration:1.3
|    |    \--- org.hamcrest:hamcrest-library:1.3 (*)
|    \--- com.google.code.findbugs:jsr305:2.0.1
+--- androidx.databinding:databinding-common:3.4.2
+--- androidx.databinding:databinding-runtime:3.4.2
|    +--- androidx.lifecycle:lifecycle-runtime:2.0.0 -> 2.1.0
|    |    +--- androidx.lifecycle:lifecycle-common:2.1.0
|    |    |    \--- androidx.annotation:annotation:1.1.0
|    |    +--- androidx.arch.core:core-common:2.1.0
|    |    |    \--- androidx.annotation:annotation:1.1.0
|    |    \--- androidx.annotation:annotation:1.1.0
|    +--- androidx.collection:collection:1.0.0
|    |    \--- androidx.annotation:annotation:1.0.0 -> 1.1.0
|    \--- androidx.databinding:databinding-common:3.4.2
+--- androidx.databinding:databinding-adapters:3.4.2
|    +--- androidx.databinding:databinding-common:3.4.2
|    \--- androidx.databinding:databinding-runtime:3.4.2 (*)
+--- org.mozilla.geckoview:geckoview-nightly-arm64-v8a:72.0.20191104094118
|    +--- org.yaml:snakeyaml:1.24
|    +--- androidx.legacy:legacy-support-v4:1.0.0
|    |    +--- androidx.core:core:1.0.0 -> 1.1.0
|    |    |    +--- androidx.annotation:annotation:1.1.0
|    |    |    +--- androidx.lifecycle:lifecycle-runtime:2.0.0 -> 2.1.0 (*)
|    |    |    +--- androidx.versionedparcelable:versionedparcelable:1.1.0
|    |    |    |    +--- androidx.annotation:annotation:1.1.0
|    |    |    |    \--- androidx.collection:collection:1.0.0 (*)
|    |    |    \--- androidx.collection:collection:1.0.0 (*)
|    |    +--- androidx.media:media:1.0.0
|    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
|    |    |    +--- androidx.core:core:1.0.0 -> 1.1.0 (*)
|    |    |    \--- androidx.versionedparcelable:versionedparcelable:1.0.0 -> 1.1.0 (*)
|    |    +--- androidx.legacy:legacy-support-core-utils:1.0.0
|    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
|    |    |    +--- androidx.core:core:1.0.0 -> 1.1.0 (*)
|    |    |    +--- androidx.documentfile:documentfile:1.0.0
|    |    |    |    \--- androidx.annotation:annotation:1.0.0 -> 1.1.0
|    |    |    +--- androidx.loader:loader:1.0.0
|    |    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
|    |    |    |    +--- androidx.core:core:1.0.0 -> 1.1.0 (*)
|    |    |    |    +--- androidx.lifecycle:lifecycle-livedata:2.0.0 -> 2.1.0
|    |    |    |    |    +--- androidx.arch.core:core-runtime:2.1.0
|    |    |    |    |    |    +--- androidx.annotation:annotation:1.1.0
|    |    |    |    |    |    \--- androidx.arch.core:core-common:[2.1.0] -> 2.1.0 (*)
|    |    |    |    |    +--- androidx.lifecycle:lifecycle-livedata-core:2.1.0
|    |    |    |    |    |    +--- androidx.lifecycle:lifecycle-common:2.1.0 (*)
|    |    |    |    |    |    +--- androidx.arch.core:core-common:2.1.0 (*)
|    |    |    |    |    |    \--- androidx.arch.core:core-runtime:2.1.0 (*)
|    |    |    |    |    \--- androidx.arch.core:core-common:2.1.0 (*)
|    |    |    |    \--- androidx.lifecycle:lifecycle-viewmodel:2.0.0 -> 2.1.0
|    |    |    |         \--- androidx.annotation:annotation:1.1.0
|    |    |    +--- androidx.localbroadcastmanager:localbroadcastmanager:1.0.0
|    |    |    |    \--- androidx.annotation:annotation:1.0.0 -> 1.1.0
|    |    |    \--- androidx.print:print:1.0.0
|    |    |         \--- androidx.annotation:annotation:1.0.0 -> 1.1.0
|    |    +--- androidx.legacy:legacy-support-core-ui:1.0.0
|    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
|    |    |    +--- androidx.core:core:1.0.0 -> 1.1.0 (*)
|    |    |    +--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
|    |    |    +--- androidx.customview:customview:1.0.0
|    |    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
|    |    |    |    \--- androidx.core:core:1.0.0 -> 1.1.0 (*)
|    |    |    +--- androidx.viewpager:viewpager:1.0.0
|    |    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
|    |    |    |    +--- androidx.core:core:1.0.0 -> 1.1.0 (*)
|    |    |    |    \--- androidx.customview:customview:1.0.0 (*)
|    |    |    +--- androidx.coordinatorlayout:coordinatorlayout:1.0.0
|    |    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
|    |    |    |    +--- androidx.core:core:1.0.0 -> 1.1.0 (*)
|    |    |    |    \--- androidx.customview:customview:1.0.0 (*)
|    |    |    +--- androidx.drawerlayout:drawerlayout:1.0.0
|    |    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
|    |    |    |    +--- androidx.core:core:1.0.0 -> 1.1.0 (*)
|    |    |    |    \--- androidx.customview:customview:1.0.0 (*)
|    |    |    +--- androidx.slidingpanelayout:slidingpanelayout:1.0.0
|    |    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
|    |    |    |    +--- androidx.core:core:1.0.0 -> 1.1.0 (*)
|    |    |    |    \--- androidx.customview:customview:1.0.0 (*)
|    |    |    +--- androidx.interpolator:interpolator:1.0.0
|    |    |    |    \--- androidx.annotation:annotation:1.0.0 -> 1.1.0
|    |    |    +--- androidx.swiperefreshlayout:swiperefreshlayout:1.0.0
|    |    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
|    |    |    |    +--- androidx.core:core:1.0.0 -> 1.1.0 (*)
|    |    |    |    \--- androidx.interpolator:interpolator:1.0.0 (*)
|    |    |    +--- androidx.asynclayoutinflater:asynclayoutinflater:1.0.0
|    |    |    |    +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
|    |    |    |    \--- androidx.core:core:1.0.0 -> 1.1.0 (*)
|    |    |    \--- androidx.cursoradapter:cursoradapter:1.0.0
|    |    |         \--- androidx.annotation:annotation:1.0.0 -> 1.1.0
|    |    \--- androidx.fragment:fragment:1.0.0
|    |         +--- androidx.core:core:1.0.0 -> 1.1.0 (*)
|    |         +--- androidx.legacy:legacy-support-core-ui:1.0.0 (*)
|    |         +--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
|    |         +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
|    |         +--- androidx.loader:loader:1.0.0 (*)
|    |         \--- androidx.lifecycle:lifecycle-viewmodel:2.0.0 -> 2.1.0 (*)
|    +--- androidx.palette:palette:1.0.0
|    |    +--- androidx.core:core:1.0.0 -> 1.1.0 (*)
|    |    \--- androidx.legacy:legacy-support-core-utils:1.0.0 (*)
|    +--- androidx.lifecycle:lifecycle-extensions:2.0.0 -> 2.1.0
|    |    +--- androidx.lifecycle:lifecycle-runtime:2.1.0 (*)
|    |    +--- androidx.arch.core:core-common:2.1.0 (*)
|    |    +--- androidx.arch.core:core-runtime:2.1.0 (*)
|    |    +--- androidx.fragment:fragment:1.0.0 (*)
|    |    +--- androidx.lifecycle:lifecycle-common:2.1.0 (*)
|    |    +--- androidx.lifecycle:lifecycle-livedata:2.1.0 (*)
|    |    +--- androidx.lifecycle:lifecycle-process:2.1.0
|    |    |    \--- androidx.lifecycle:lifecycle-runtime:2.1.0 (*)
|    |    +--- androidx.lifecycle:lifecycle-service:2.1.0
|    |    |    \--- androidx.lifecycle:lifecycle-runtime:2.1.0 (*)
|    |    \--- androidx.lifecycle:lifecycle-viewmodel:2.1.0 (*)
|    \--- androidx.lifecycle:lifecycle-common-java8:2.0.0
|         +--- androidx.lifecycle:lifecycle-common:2.0.0 -> 2.1.0 (*)
|         \--- androidx.annotation:annotation:1.0.0 -> 1.1.0
+--- androidx.test:runner:{strictly 1.1.0-alpha4} -> 1.1.0-alpha4 (c)
+--- androidx.annotation:annotation:{strictly 1.1.0} -> 1.1.0 (c)
+--- androidx.test:monitor:{strictly 1.1.0-alpha4} -> 1.1.0-alpha4 (c)
+--- junit:junit:{strictly 4.12} -> 4.12 (c)
+--- org.hamcrest:hamcrest-core:{strictly 1.3} -> 1.3 (c)
+--- net.sf.kxml:kxml2:{strictly 2.3.0} -> 2.3.0 (c)
+--- androidx.test.espresso:espresso-core:{strictly 3.1.0-alpha4} -> 3.1.0-alpha4 (c)
+--- androidx.test.espresso:espresso-idling-resource:{strictly 3.1.0-alpha4} -> 3.1.0-alpha4 (c)
+--- com.squareup:javawriter:{strictly 2.1.1} -> 2.1.1 (c)
+--- javax.inject:javax.inject:{strictly 1} -> 1 (c)
+--- org.hamcrest:hamcrest-library:{strictly 1.3} -> 1.3 (c)
+--- org.hamcrest:hamcrest-integration:{strictly 1.3} -> 1.3 (c)
+--- com.google.code.findbugs:jsr305:{strictly 2.0.1} -> 2.0.1 (c)
+--- androidx.databinding:databinding-common:{strictly 3.4.2} -> 3.4.2 (c)
+--- androidx.databinding:databinding-runtime:{strictly 3.4.2} -> 3.4.2 (c)
+--- androidx.lifecycle:lifecycle-runtime:{strictly 2.1.0} -> 2.1.0 (c)
+--- androidx.lifecycle:lifecycle-common:{strictly 2.1.0} -> 2.1.0 (c)
+--- androidx.arch.core:core-common:{strictly 2.1.0} -> 2.1.0 (c)
+--- androidx.collection:collection:{strictly 1.0.0} -> 1.0.0 (c)
+--- androidx.databinding:databinding-adapters:{strictly 3.4.2} -> 3.4.2 (c)
+--- org.mozilla.geckoview:geckoview-nightly-arm64-v8a:{strictly 72.0.20191104094118} -> 72.0.20191104094118 (c)
+--- org.yaml:snakeyaml:{strictly 1.24} -> 1.24 (c)
+--- androidx.legacy:legacy-support-v4:{strictly 1.0.0} -> 1.0.0 (c)
+--- androidx.core:core:{strictly 1.1.0} -> 1.1.0 (c)
+--- androidx.versionedparcelable:versionedparcelable:{strictly 1.1.0} -> 1.1.0 (c)
+--- androidx.media:media:{strictly 1.0.0} -> 1.0.0 (c)
+--- androidx.legacy:legacy-support-core-utils:{strictly 1.0.0} -> 1.0.0 (c)
+--- androidx.documentfile:documentfile:{strictly 1.0.0} -> 1.0.0 (c)
+--- androidx.loader:loader:{strictly 1.0.0} -> 1.0.0 (c)
+--- androidx.lifecycle:lifecycle-livedata:{strictly 2.1.0} -> 2.1.0 (c)
+--- androidx.arch.core:core-runtime:{strictly 2.1.0} -> 2.1.0 (c)
+--- androidx.lifecycle:lifecycle-livedata-core:{strictly 2.1.0} -> 2.1.0 (c)
+--- androidx.lifecycle:lifecycle-viewmodel:{strictly 2.1.0} -> 2.1.0 (c)
+--- androidx.localbroadcastmanager:localbroadcastmanager:{strictly 1.0.0} -> 1.0.0 (c)
+--- androidx.print:print:{strictly 1.0.0} -> 1.0.0 (c)
+--- androidx.legacy:legacy-support-core-ui:{strictly 1.0.0} -> 1.0.0 (c)
+--- androidx.customview:customview:{strictly 1.0.0} -> 1.0.0 (c)
+--- androidx.viewpager:viewpager:{strictly 1.0.0} -> 1.0.0 (c)
+--- androidx.coordinatorlayout:coordinatorlayout:{strictly 1.0.0} -> 1.0.0 (c)
+--- androidx.drawerlayout:drawerlayout:{strictly 1.0.0} -> 1.0.0 (c)
+--- androidx.slidingpanelayout:slidingpanelayout:{strictly 1.0.0} -> 1.0.0 (c)
+--- androidx.interpolator:interpolator:{strictly 1.0.0} -> 1.0.0 (c)
+--- androidx.swiperefreshlayout:swiperefreshlayout:{strictly 1.0.0} -> 1.0.0 (c)
+--- androidx.asynclayoutinflater:asynclayoutinflater:{strictly 1.0.0} -> 1.0.0 (c)
+--- androidx.cursoradapter:cursoradapter:{strictly 1.0.0} -> 1.0.0 (c)
+--- androidx.fragment:fragment:{strictly 1.0.0} -> 1.0.0 (c)
+--- androidx.palette:palette:{strictly 1.0.0} -> 1.0.0 (c)
+--- androidx.lifecycle:lifecycle-extensions:{strictly 2.1.0} -> 2.1.0 (c)
+--- androidx.lifecycle:lifecycle-process:{strictly 2.1.0} -> 2.1.0 (c)
+--- androidx.lifecycle:lifecycle-service:{strictly 2.1.0} -> 2.1.0 (c)
+--- androidx.lifecycle:lifecycle-common-java8:{strictly 2.0.0} -> 2.0.0 (c)
+--- com.google.vr:sdk-base:{strictly 1.190.0} -> 1.190.0 (c)
+--- org.jetbrains.kotlin:kotlin-android-extensions-runtime:{strictly 1.3.50} -> 1.3.50 (c)
+--- org.jetbrains.kotlin:kotlin-stdlib:{strictly 1.3.50} -> 1.3.50 (c)
+--- org.jetbrains.kotlin:kotlin-stdlib-common:{strictly 1.3.50} -> 1.3.50 (c)
+--- org.jetbrains:annotations:{strictly 13.0} -> 13.0 (c)
+--- jp.co.omronsoft.openwnn:openwnn:{strictly 1.3.7} -> 1.3.7 (c)
+--- androidx.cardview:cardview:{strictly 1.0.0} -> 1.0.0 (c)
+--- androidx.vectordrawable:vectordrawable:{strictly 1.0.0} -> 1.0.0 (c)
+--- androidx.constraintlayout:constraintlayout:{strictly 2.0.0-alpha2} -> 2.0.0-alpha2 (c)
+--- androidx.recyclerview:recyclerview:{strictly 1.0.0-rc01} -> 1.0.0-rc01 (c)
+--- androidx.constraintlayout:constraintlayout-solver:{strictly 2.0.0-alpha2} -> 2.0.0-alpha2 (c)
+--- com.google.code.gson:gson:{strictly 2.8.5} -> 2.8.5 (c)
+--- androidx.room:room-runtime:{strictly 2.2.0} -> 2.2.0 (c)
+--- androidx.room:room-common:{strictly 2.2.0} -> 2.2.0 (c)
+--- androidx.sqlite:sqlite-framework:{strictly 2.0.1} -> 2.0.1 (c)
+--- androidx.sqlite:sqlite:{strictly 2.0.1} -> 2.0.1 (c)
+--- com.github.mozilla:mozillaspeechlibrary:{strictly 1.0.6} -> 1.0.6 (c)
+--- org.gagravarr:vorbis-java-core:{strictly 0.8} -> 0.8 (c)
+--- com.github.axet:opus:{strictly 1.0.2} -> 1.0.2 (c)
+--- com.github.axet:libopus:{strictly 1.2-2} -> 1.2-2 (c)
+--- com.github.axet:jssrc:{strictly 1.0.2-2} -> 1.0.2-2 (c)
+--- org.apache.commons:commons-math3:{strictly 3.6.1} -> 3.6.1 (c)
+--- com.loopj.android:android-async-http:{strictly 1.4.9} -> 1.4.9 (c)
+--- cz.msebera.android:httpclient:{strictly 4.3.6} -> 4.3.6 (c)
+--- org.mozilla.components:service-telemetry:{strictly 19.0.1} -> 19.0.1 (c)
+--- org.mozilla.components:support-base:{strictly 19.0.1} -> 19.0.1 (c)
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:{strictly 1.3.50} -> 1.3.50 (c)
+--- org.mozilla.components:concept-fetch:{strictly 19.0.1} -> 19.0.1 (c)
+--- org.mozilla.components:browser-errorpages:{strictly 19.0.1} -> 19.0.1 (c)
+--- org.mozilla.components:browser-search:{strictly 19.0.1} -> 19.0.1 (c)
+--- org.jetbrains.kotlinx:kotlinx-coroutines-android:{strictly 1.3.2} -> 1.3.2 (c)
+--- org.jetbrains.kotlinx:kotlinx-coroutines-core:{strictly 1.3.2} -> 1.3.2 (c)
+--- org.mozilla.components:browser-storage-sync:{strictly 19.0.1} -> 19.0.1 (c)
+--- org.mozilla.appservices:places:{strictly 0.42.0} -> 0.42.0 (c)
+--- org.mozilla.appservices:sync15:{strictly 0.42.0} -> 0.42.0 (c)
+--- org.mozilla.appservices:full-megazord:{strictly 0.42.0} -> 0.42.0 (c)
+--- org.mozilla.components:concept-storage:{strictly 19.0.1} -> 19.0.1 (c)
+--- org.mozilla.components:concept-sync:{strictly 19.0.1} -> 19.0.1 (c)
+--- org.mozilla.components:service-glean:{strictly 19.0.1} -> 19.0.1 (c)
+--- org.mozilla.telemetry:glean:{strictly 19.1.0} -> 19.1.0 (c)
+--- androidx.work:work-runtime-ktx:{strictly 2.2.0} -> 2.2.0 (c)
+--- androidx.work:work-runtime:{strictly 2.2.0} -> 2.2.0 (c)
+--- com.google.guava:listenablefuture:{strictly 1.0} -> 1.0 (c)
+--- org.mozilla.components:lib-fetch-httpurlconnection:{strictly 19.0.1} -> 19.0.1 (c)
+--- org.mozilla.components:browser-domains:{strictly 19.0.1} -> 19.0.1 (c)
+--- org.mozilla.components:service-firefox-accounts:{strictly 19.0.1} -> 19.0.1 (c)
+--- org.mozilla.appservices:fxaclient:{strictly 0.42.0} -> 0.42.0 (c)
+--- org.mozilla.components:ui-autocomplete:{strictly 19.0.1} -> 19.0.1 (c)
+--- org.mozilla.components:support-rustlog:{strictly 19.0.1} -> 19.0.1 (c)
+--- org.mozilla.components:support-rusthttp:{strictly 19.0.1} -> 19.0.1 (c)
+--- org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:{strictly 1.2.1} -> 1.2.1 (c)
+--- com.readystatesoftware.sqliteasset:sqliteassethelper:{strictly 2.0.1} -> 2.0.1 (c)
+--- com.jakewharton:disklrucache:{strictly 2.0.2} -> 2.0.2 (c)
+--- com.google.vr:sdk-base:1.190.0
+--- org.jetbrains.kotlin:kotlin-android-extensions-runtime:1.3.31 -> 1.3.50
|    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.50
|         +--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.50
|         \--- org.jetbrains:annotations:13.0
+--- jp.co.omronsoft.openwnn:openwnn:1.3.7
+--- androidx.lifecycle:lifecycle-runtime:2.0.0 -> 2.1.0 (*)
+--- androidx.lifecycle:lifecycle-extensions:2.0.0 -> 2.1.0 (*)
+--- androidx.cardview:cardview:1.0.0
|    \--- androidx.annotation:annotation:1.0.0 -> 1.1.0
+--- :appcompat
+--- androidx.vectordrawable:vectordrawable:1.0.0
|    +--- androidx.annotation:annotation:1.0.0 -> 1.1.0
|    \--- androidx.core:core:1.0.0 -> 1.1.0 (*)
+--- androidx.annotation:annotation:1.0.0 -> 1.1.0
+--- androidx.constraintlayout:constraintlayout:2.0.0-alpha2
|    +--- androidx.recyclerview:recyclerview:1.0.0-rc01
|    |    +--- androidx.annotation:annotation:1.0.0-rc01 -> 1.1.0
|    |    +--- androidx.core:core:1.0.0-rc01 -> 1.1.0 (*)
|    |    \--- androidx.legacy:legacy-support-core-ui:1.0.0-rc01 -> 1.0.0 (*)
|    \--- androidx.constraintlayout:constraintlayout-solver:2.0.0-alpha2
+--- com.google.code.gson:gson:2.8.5
+--- androidx.room:room-runtime:2.2.0
|    +--- androidx.room:room-common:[2.2.0] -> 2.2.0
|    |    \--- androidx.annotation:annotation:1.1.0
|    +--- androidx.sqlite:sqlite-framework:2.0.1
|    |    +--- androidx.annotation:annotation:1.0.2 -> 1.1.0
|    |    \--- androidx.sqlite:sqlite:2.0.1
|    |         \--- androidx.annotation:annotation:1.0.2 -> 1.1.0
|    +--- androidx.sqlite:sqlite:2.0.1 (*)
|    \--- androidx.arch.core:core-runtime:2.0.1 -> 2.1.0 (*)
+--- com.github.mozilla:mozillaspeechlibrary:1.0.6
|    +--- org.gagravarr:vorbis-java-core:0.8
|    +--- com.github.axet:opus:1.0.2
|    |    \--- com.github.axet:libopus:1.2-2
|    +--- com.github.axet:jssrc:1.0.2-2
|    +--- org.apache.commons:commons-math3:3.6.1
|    \--- com.loopj.android:android-async-http:1.4.9
|         \--- cz.msebera.android:httpclient:4.3.6
+--- org.mozilla.components:service-telemetry:19.0.1
+--- org.mozilla.components:browser-errorpages:19.0.1
+--- org.mozilla.components:browser-search:19.0.1
+--- org.mozilla.components:browser-storage-sync:19.0.1
|    +--- org.mozilla.appservices:places:0.42.0
|    |    +--- org.mozilla.appservices:sync15:0.42.0
|    |    \--- org.mozilla.appservices:full-megazord:0.42.0
|    +--- org.mozilla.components:concept-storage:19.0.1
|    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.2
|    |         +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.50 (*)
|    |         \--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.2
|    |              +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.50 (*)
|    |              \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.50
|    \--- org.mozilla.components:concept-sync:19.0.1
|         +--- org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.2 (*)
|         \--- org.mozilla.components:support-base:19.0.1
+--- org.mozilla.components:browser-domains:19.0.1
+--- org.mozilla.components:service-firefox-accounts:19.0.1
|    +--- org.mozilla.components:concept-sync:19.0.1 (*)
|    +--- org.mozilla.appservices:fxaclient:0.42.0
|    |    \--- org.mozilla.appservices:full-megazord:0.42.0
|    \--- org.mozilla.components:support-base:19.0.1
+--- org.mozilla.components:ui-autocomplete:19.0.1
+--- org.mozilla.components:concept-fetch:19.0.1
+--- org.mozilla.components:lib-fetch-httpurlconnection:19.0.1
+--- org.mozilla.components:support-rustlog:19.0.1
|    \--- org.mozilla.components:support-base:19.0.1
+--- org.mozilla.components:support-rusthttp:19.0.1
|    \--- org.mozilla.components:concept-fetch:19.0.1
+--- org.mozilla.components:service-glean:19.0.1
|    \--- org.mozilla.telemetry:glean:19.1.0
+--- androidx.work:work-runtime-ktx:null -> 2.2.0
|    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.40 -> 1.3.50 (*)
|    +--- org.jetbrains.kotlinx:kotlinx-coroutines-android:1.1.1 -> 1.3.2 (*)
|    \--- androidx.work:work-runtime:[2.2.0] -> 2.2.0
|         +--- com.google.guava:listenablefuture:1.0
|         +--- androidx.lifecycle:lifecycle-livedata:2.0.0 -> 2.1.0 (*)
|         +--- androidx.room:room-runtime:2.1.0 -> 2.2.0 (*)
|         +--- androidx.core:core:1.0.0 -> 1.1.0 (*)
|         \--- androidx.lifecycle:lifecycle-service:2.0.0 -> 2.1.0 (*)
+--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.3.31 -> 1.3.50
|    \--- org.jetbrains.kotlin:kotlin-stdlib:1.3.50 (*)
+--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.2.1 -> 1.3.2 (*)
+--- org.jetbrains.kotlinx:kotlinx-coroutines-jdk8:1.2.1
|    +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.30 -> 1.3.50 (*)
|    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.2.1 -> 1.3.2 (*)
+--- com.readystatesoftware.sqliteasset:sqliteassethelper:2.0.1
\--- com.jakewharton:disklrucache:2.0.2
```

**Comment by mreid-moz** [comment]
Requesting review from @Dexterp37 too, since I don't see `org.mozilla.components:support-sync-telemetry` in the list above (thanks @mdboom !).

**Comment by Dexterp37** [comment]
> 
> 
> Here's the complete dependencies list of FirefoxReality, for reference:
> 
> ```
> ...
> +--- org.mozilla.components:browser-storage-sync:19.0.1
> |    +--- org.mozilla.appservices:places:0.42.0
> |    |    +--- org.mozilla.appservices:sync15:0.42.0
> |    |    \--- org.mozilla.appservices:full-megazord:0.42.0
> |    +--- org.mozilla.components:concept-storage:19.0.1
> |    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.2
> |    |         +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.50 (*)
> |    |         \--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.2
> |    |              +--- org.jetbrains.kotlin:kotlin-stdlib:1.3.50 (*)
> |    |              \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.3.50
> |    \--- org.mozilla.components:concept-sync:19.0.1
> |         +--- org.jetbrains.kotlinx:kotlinx-coroutines-android:1.3.2 (*)
> |         \--- org.mozilla.components:support-base:19.0.1
> ...
> ```

Woha, that's interesting. So, we know that `browser-storage-sync` [depends on `support-sync-telemetry`](https://github.com/mozilla-mobile/android-components/blob/ef631b6df715d82374845ccf97ab09aab5d09408/components/browser/storage-sync/build.gradle#L50).

I'm not sure why it's not being listed as a dependency here. Maybe it's because we're depending with `implementation project()`?

Weird. Another terror story in this Gradle hell. @mdboom , clues?

**Comment by mdboom** [comment]
My best guess is that FirefoxReality has a couple dozen build configurations and I picked the wrong one.  Other configurations *do* seem to have `support-sync-telemetry`.  (So some builds maybe include sync and others don't).  As long as some of them do, I think we should include it (and if some don't sent sync telemetry, that's just fine...)  I think it's the right thing to include `support-sync-telemetry` on that basis.

**Pull request merged**
