### PR TITLE
Add new locations for MozillaVPN metric files

### PR DESCRIPTION
**Pull request by brizental**

### CODE REVIEW

**Review by Dexterp37 — APPROVED** [review]
@brizental did you dry run this locally to make sure it doesn't break?

**Comment by brizental** [comment]
> @brizental did you dry run this locally to make sure it doesn't break?

Nope 👀 Aren't the CI checks enough?

**Comment by Dexterp37** [comment]
> > @brizental did you dry run this locally to make sure it doesn't break?
> 
> Nope 👀 Aren't the CI checks enough?

No :( I run this locally and everything works fine. Merging

**Comment by brizental** [comment]
> No :( I run this locally and everything works fine. Merging

Thank you ❤️

**Pull request merged**
