### PR TITLE
Mark use counters as enabled on release (opt-out)

### PR DESCRIPTION
**Pull request by badboy**
This was done on desktop in [bug 1510566](https://bugzilla.mozilla.org/show_bug.cgi?id=1510566), but we forgot to import it here
as well.

### CODE REVIEW

**Comment by Dexterp37** [comment]
Interesting. Some failures are unrelated here, e.g. the ones related to the git repository and the required 'expired' key. Let me fix this in a separate PR.

**Comment by badboy** [comment]
Yeah, looks like the glean parser recently turned `expires` into a required attribute. Had the same test failures locally.
Leaving that for you to fix here. :)

**Comment by Dexterp37** [comment]
#78 was merged. You're good to go!

**Comment by georgf** [comment]
Cheers for following up!
Note that the use counters are only enabled on release from Firefox 65+.
Is this reflected in the data here?

**Comment by fbertsch** [comment]
@badboy @Dexterp37 do we still want to get this in?

**Comment by badboy** [comment]
Yes, let's get that in. I'm not sure how the probe-scraper determines the first version a probe was introduced in though. Georg is right that we enabled release use counters in 65. Is there any way we can add a small special case into the code there?

**Comment by fbertsch** [comment]
@badboy just to be clear: you'd like all use-counters to have a definition from _before_ 65 that marks it as `opt-in`, and a definition _after_ 65 that marks it as `opt-out` (for the ones that were available before 65)?

**Comment by badboy** [comment]
that would be the technically correct solution, yes.

**Comment by fbertsch** [comment]
Okay, it should be relatively straightforward. It will happen [in this piece](https://github.com/mozilla/probe-scraper/blob/master/probe_scraper/parsers/histograms.py#L9). You will need to add the `version` as a parameter to that function, from [here](https://github.com/mozilla/probe-scraper/blob/master/probe_scraper/parsers/histograms.py#L71).

Then in the [code that checks for opt-in/opt-out](https://github.com/mozilla/probe-scraper/blob/master/probe_scraper/parsers/histograms.py#L48), check if it's a use-counter and if it's before/after 65.

**Comment by badboy** [comment]
He, I even ran it across a wider range! Looks good though:

**Comment by fbertsch** [comment]
That's great! Let's get this in.

**Pull request merged**
